# Generated by Django 2.2 on 2019-04-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190417_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='total_i_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
