# Generated by Django 2.2 on 2019-04-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(db_index=True, default=0, max_length=15),
            preserve_default=False,
        ),
    ]
