# Generated by Django 2.2 on 2019-04-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='b_price',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=10),
            preserve_default=False,
        ),
    ]
